# https://travis-ci.org/
language: python
python: "2.7"

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
