#
# Copyright (c) 2017 Paul Borza
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#

language: python
python: "2.7"

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

script:
  - ansible-playbook tests/vagrant.yml --syntax-check
