#
# Copyright (c) 2017-present Paul Borza
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#

language: python
python: "2.7"

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

script:
  - ansible --version
  - ansible-playbook tests/vagrant.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
