#
# Copyright (c) 2017-present Paul Borza
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#

- name: install ubuntu packages
  become: true
  apt: name={{item}} update_cache=yes state=installed force=yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: add docker gpg key
  become: true
  apt_key: 
    url: https://apt.dockerproject.org/gpg

- name: add docker repository
  become: true
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-{{ansible_distribution_release}} main' state=present

- name: install docker engine
  become: true
  apt: name=docker-engine update_cache=yes state=installed force=yes

# docker-py is required by the docker ansible module.
- name: install docker python package
  become: true
  pip: name=docker-py
