#
# Copyright (c) 2017-present Paul Borza
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#

- import_tasks: "{{ansible_distribution|lower}}.yml"
