#
# Copyright (c) 2017 Paul Borza
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#

- name: install ubuntu packages
  become: true
  apt: name={{item}} update_cache=yes state=installed force=yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: add docker gpg key
  become: true
  apt_key: 
    url: https://apt.dockerproject.org/gpg

- name: add trusty docker repository
  become: true
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
  when: ansible_distribution_release == 'trusty'

- name: add xenial docker repository
  become: true
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present
  when: ansible_distribution_release == 'xenial'

- name: install docker engine
  become: true
  apt: name=docker-engine update_cache=yes state=installed force=yes

# docker-py is required by the docker ansible module.
- name: install docker python package
  become: true
  pip: name=docker-py
